[package]
name = "as-link"
version = "0.1.0"
authors = ["Willem Wyndham <willem@cs.umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.19.0"
wasmtime-wasi = "0.19.1"
anyhow = "1.0.32"